id: P9389BFBB
initial_creation_type: ocr
source_metadata:
  volumes:
    9b8831dadbe74ff6a62c4e444113a958:
      base_file: v050.txt
      image_group_id: I1PD95895
      title: ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་སྟོང་ཕྲག་ཉི་ཤུ་ལྔ་པ།
      total_pages: 1666
      volume_number: 50
